# bash test_totalseg_cmd.sh Task011_BTCV
# bash test_totalseg_cmd.sh Task011_BTCV
# bash test_totalseg_cmd.sh Task020_AbdomenCT1K
# bash test_totalseg_cmd.sh Task003_Liver
# bash test_totalseg_cmd.sh Task007_Pancreas
# bash test_totalseg_cmd.sh Task009_Spleen
# bash test_totalseg_cmd.sh Task021_KiTS2021
# bash test_totalseg_cmd.sh Task154_RibFrac
# bash test_totalseg_cmd.sh Task083_VerSe2020
# bash test_totalseg_cmd.sh Task030_CT_ORG
# bash test_totalseg_cmd.sh Task037_CHAOS_Task_3_5_Variant1
# bash test_totalseg_cmd.sh Task031_AMOS_MR
# bash test_totalseg_cmd.sh Task558_Totalsegmentator_dataset
